## Website
title:              Simple Blog
subtitle:           A static blog
host:               http://localhost
root:               /

## Output
archive_dir:        archive
category_dir:       category
tag_dir:            tag
post_link:          post/:year/:month/:day/:name.html
page_link:          page/:name
paginate:           10

## Engine
latex:              true
subscribe:          true

## Server
port:               4040
password:           false
